# Generated by Django 5.0 on 2024-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pop_skills_fsprogrammer_alter_pop_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('count', models.CharField(max_length=12, verbose_name='кол-во вакансий')),
            ],
            options={
                'verbose_name': 'Кол-во вакансий для всех проф',
                'verbose_name_plural': 'Кол-во вакансий для всех проф',
            },
        ),
        migrations.CreateModel(
            name='vacancy_fsprog_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('count', models.CharField(max_length=12, verbose_name='кол-во вакансий')),
            ],
            options={
                'verbose_name': 'Кол-во вакансий для фуллстак',
                'verbose_name_plural': 'Кол-во вакансий для фуллстак',
            },
        ),
        migrations.CreateModel(
            name='zp_fsprog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('salary', models.CharField(max_length=12, verbose_name='заработная плата')),
            ],
            options={
                'verbose_name': 'ЗП для фуллстак по годам',
                'verbose_name_plural': 'ЗП для фуллстак по годам',
            },
        ),
        migrations.CreateModel(
            name='zp_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='год')),
                ('salary', models.CharField(max_length=12, verbose_name='заработная плата')),
            ],
            options={
                'verbose_name': 'ЗП для всех проф по годам',
                'verbose_name_plural': 'ЗП для всех проф по годам',
            },
        ),
    ]
